Repository sonata-project/form-extensions, pull requests merged in 2022-05, with the labels that each got.

#322 Add rector
  .gitattributes
  .github/workflows/qa.yaml
  Makefile
  composer.json
  rector.php
  src/Date/MomentFormatConverter.php
  src/EventListener/ResizeFormListener.php
  src/Test/AbstractWidgetTestCase.php
  src/Type/BasePickerType.php
  src/Validator/ErrorElement.php
  src/Validator/InlineValidator.php
  tests/EventListener/FixCheckboxDataListenerTest.php
  tests/EventListener/ResizeFormListenerTest.php
  tests/Type/BasePickerTypeTest.php
  tests/Type/ImmutableArrayTypeTest.php
  tests/Validator/Constraints/InlineConstraintTest.php
  tests/Validator/ErrorElementTest.php
  tests/Validator/InlineValidatorTest.php
Labels: pedantic

#321 Drop older versions
  .github/workflows/test.yaml
  composer.json
  phpstan.neon.dist
  src/Bridge/Symfony/Resources/config/date.php
  src/Bridge/Symfony/Resources/config/form_types.php
  src/Bridge/Symfony/Resources/config/validator.php
Labels: major

#325 Add missing dep
  composer.json
Labels: pedantic

#326 Upgrade to PHP 8 minimum
  .github/workflows/test.yaml
  composer.json
  rector.php
  src/EventListener/ResizeFormListener.php
  src/Fixtures/StubTranslator.php
  src/Type/BasePickerType.php
  src/Type/BaseStatusType.php
  src/Validator/Constraints/InlineConstraint.php
  src/Validator/ErrorElement.php
  src/Validator/InlineValidator.php
  tests/DataTransformer/BooleanTypeToBooleanTransformerTest.php
  tests/EventListener/FixCheckboxDataListenerTest.php
  tests/Fixtures/Bundle/Entity/Foo.php
  tests/Validator/Constraints/InlineConstraintTest.php
Labels: major

#328 Narrow form type options
  src/Type/BasePickerType.php
  src/Type/BooleanType.php
  src/Type/CollectionType.php
  src/Type/DatePickerType.php
  src/Type/DateRangePickerType.php
  src/Type/DateRangeType.php
  src/Type/DateTimePickerType.php
  src/Type/DateTimeRangePickerType.php
  src/Type/DateTimeRangeType.php
  tests/Type/BooleanTypeTest.php
Labels: major

#336 Add twig extension to canonicalize locales for momentjs
  assets/scss/app.scss
  src/Bridge/Symfony/DependencyInjection/SonataFormExtension.php
  src/Bridge/Symfony/Resources/config/twig.php
  src/Twig/CanonicalizeRuntime.php
  src/Twig/Extension/CanonicalizeExtension.php
  tests/Twig/CanonicalizeRuntimeTest.php
Labels: minor

#337 Add support for doctrine/persistence 3
  composer.json
Labels: pedantic

#343 Revert "Revert "Add rector (#322)""
  .gitattributes
  .github/workflows/qa.yaml
  Makefile
  composer.json
  rector.php
  src/Date/MomentFormatConverter.php
  src/EventListener/ResizeFormListener.php
  src/Test/AbstractWidgetTestCase.php
  src/Type/BasePickerType.php
  src/Validator/ErrorElement.php
  src/Validator/InlineValidator.php
  tests/EventListener/FixCheckboxDataListenerTest.php
  tests/EventListener/ResizeFormListenerTest.php
  tests/Type/BasePickerTypeTest.php
  tests/Type/ImmutableArrayTypeTest.php
  tests/Validator/Constraints/InlineConstraintTest.php
  tests/Validator/ErrorElementTest.php
  tests/Validator/InlineValidatorTest.php
Labels: pedantic

#340 Remove compatibility with PHP 7.3
  composer.json
Labels: minor

#347 Restore PHP 7.3 compatibility
  .github/workflows/test.yaml
  src/Twig/CanonicalizeRuntime.php
  tests/Twig/CanonicalizeRuntimeTest.php
Labels: patch

#349 Revert "Restore PHP 7.3 compatibility"
  .github/workflows/test.yaml
  src/Twig/CanonicalizeRuntime.php
  tests/Twig/CanonicalizeRuntimeTest.php
Labels: pedantic

#350 Revert "Revert "Revert "Revert "Add rector (#322)""""
  .gitattributes
  .github/workflows/qa.yaml
  Makefile
  composer.json
  rector.php
  src/Date/MomentFormatConverter.php
  src/EventListener/ResizeFormListener.php
  src/Test/AbstractWidgetTestCase.php
  src/Type/BasePickerType.php
  src/Validator/ErrorElement.php
  src/Validator/InlineValidator.php
  tests/EventListener/FixCheckboxDataListenerTest.php
  tests/EventListener/ResizeFormListenerTest.php
  tests/Type/BasePickerTypeTest.php
  tests/Type/ImmutableArrayTypeTest.php
  tests/Validator/Constraints/InlineConstraintTest.php
  tests/Validator/ErrorElementTest.php
  tests/Validator/InlineValidatorTest.php
Labels: pedantic

#351 Revert "Revert "Remove compatibility with PHP 7.3""
  composer.json
Labels: minor

#354 Update doc
  UPGRADE-2.0.md
  docs/reference/form_types.rst
  docs/reference/installation.rst
  docs/reference/testing.rst
Labels: docs

#355 Fix upgrade note
  UPGRADE-2.0.md
Labels: pedantic

#360 Add some final keyword and typehint
  src/Bridge/Symfony/DependencyInjection/Configuration.php
  src/DataTransformer/BooleanTypeToBooleanTransformer.php
  src/Date/MomentFormatConverter.php
  src/Validator/Constraints/InlineConstraint.php
  src/Validator/ErrorElement.php
  src/Validator/InlineValidator.php
  tests/DataTransformer/BooleanTypeToBooleanTransformerTest.php
  tests/Type/DatePickerTypeTest.php
  tests/Type/DateTimePickerTypeTest.php
  tests/Validator/ErrorElementTest.php
Labels: major
