Repository sonata-project/form-extensions, pull requests merged in 2023-04, with the labels that each got.

#421 DevKit updates for 1.x branch
  .github/workflows/auto-merge-dev-kit.yaml
Labels: automerge

#423 DevKit updates for 1.x branch
  .github/workflows/auto-merge-dev-kit.yaml
Labels: automerge

#424 DevKit updates for 1.x branch
  README.md
Labels: automerge

#416 Handle moment locale when request locale has equal language and country parts
  src/Twig/CanonicalizeRuntime.php
  tests/Twig/CanonicalizeRuntimeTest.php
Labels: patch

#425 Fix CHANGELOG
  CHANGELOG.md
Labels: pedantic

#426 Release 1.19.1
  CHANGELOG.md
Labels: dev-kit
