Repository sonata-project/form-extensions, pull requests merged in 2023-05, with the labels that each got.

#429 DevKit updates for 2.x branch
  .github/workflows/frontend.yaml
Labels: automerge, dev-kit

#431 Manual merge
  .github/workflows/documentation.yaml
  .readthedocs.yaml
  docs/conf.py
  docs/reference/conditional_validation.rst
  docs/reference/form_types.rst
  docs/reference/installation.rst
  docs/requirements.txt
Labels: pedantic

#432 Up rector to 0.16
  composer.json
Labels: pedantic

#433 Update docs, remove NEXT_MAJOR comments
  UPGRADE-2.0.md
  docs/images/color.png
  docs/reference/form_types.rst
  src/Bridge/Symfony/DependencyInjection/SonataFormExtension.php
  src/Bridge/Symfony/Resources/config/twig.php
  src/Twig/CanonicalizeRuntime.php
  src/Twig/Extension/CanonicalizeExtension.php
  tests/Twig/CanonicalizeRuntimeTest.php
Labels: major

#434 Release 2.0.0-alpha-1
  CHANGELOG.md
Labels: dev-kit
