Repository sonata-project/form-extensions, pull requests merged in 2025-05, with the labels that each got.

#532 DevKit updates for 2.x branch
  phpstan.neon.dist
Labels: automerge, dev-kit

#533 DevKit updates for 3.x branch
  phpstan.neon.dist
Labels: automerge, dev-kit

#530 Patch 1
  src/Bridge/Symfony/Resources/translations/SonataFormBundle.bg.xliff
Labels: patch

#535 Bump psalm and phpstan
  composer.json
  phpstan-baseline.neon
  phpstan.neon.dist
  psalm.xml
  src/Type/DateTimeRangePickerType.php
  src/Validator/ErrorElement.php
  tests/EventListener/FixCheckboxDataListenerTest.php
Labels: minor

#538 DevKit updates for 2.x branch
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/test.yaml
  Makefile
Labels: automerge, dev-kit
